# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.warning.mode=none

# Shared mod metadata (inherited by all subprojects)
maven_group=com.spaceagle17
archives_base_name=iris_shader_folder
mod_id=iris_shader_folder
mod_name=Iris Shader Folder
mod_license=MIT
mod_group_id=com.spaceagle17
mod_authors=SpacEagle17
mod_description=Hides specified shader packs in Iris shaders menu

# Publishing Configuration
curseforge_project_id=1351246
modrinth_project_id=yv6sGJzN
do_live_publishing=true
